### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MTRNord** [marius311/cosmohome#15]
Hi I am working on an fork (to use the docker boinc the right way ;) ) and I wonder how to create the forum.

Because if I run `php create_forums.php` it gives:

```
Database Error<br>
Database Error<br>
Database Error<br>
Database Error<br>
Database Error<br>
Database Error<br>
Database Error<br>
Database Error<br>
```

Or do I miss something?

**Comment by MTRNord** [comment]
Ok somehow it seems to have worked but frontpage (News thingy) does not.

**Comment by marius311** [comment]
Hm odd, I just tested 1) starting up a fresh project 2) deleting the "die" line in create_forums.php and 3) running `php create_forums.php` and it seems to work, including the frontpage News thing. It must have to do with the database error you were seeing initially. Is the mysql container working OK? You can try running `mysql -h mysql boincserver` from the apache container to see if it connects correctly.

**Comment by marius311** [comment]
Also, was the News forum in particular created? That's the one it reads for the front page.

**Comment by marius311** [comment]
Ahhhh sorry just realized, are you're running cosmohome or the generic boinc-server-docker? I think indeed cosmohome's `create_forums.php` doesn't correctly create the News forum, since I just did that by hand for the real site way back when.

**Comment by MTRNord** [comment]
I am running an fork of cosmohome with its forum script :)

**Comment by MTRNord** [comment]
So that means I just have to copy some lines of the original forums script that is made by boinc? (Or just run the original one to generate the News)

**Comment by marius311** [comment]
Yep, OK, that's the problem then. Basically you can see no News forum gets created starting https://github.com/marius311/cosmohome/blob/master/html/ops/create_forums.php#L59. I'll fix that to be more consistent with the actual site.

**Comment by marius311** [comment]
Ok, should be fixed by 150ca5d76a36efdced2a736672b0f1c13064ff1f. 

I also noticed that you'll get the Database error message above if you try to run `create_forums.php` more than once, that might be what had happened.

**Comment by MTRNord** [comment]
thanks :+1:

**Comment by MTRNord** [comment]
Another Question: Downloads require ssl am I right? or is there another thing that could cause:

`3384   ProjectStreet@Car   01.10.2016 18:07:21 Giving up on download of vboxwrapper_26197_windows_x86_64.exe: permanent HTTP error`

and

Marcel-PC

`3385   ProjectStreet@Car   01.10.2016 18:07:21 Giving up on download of vm_isocontext_v1.0.0.iso: permanent HTTP error`

?

(I did not yet install an ssl cert. So that could cause issues but I am not shure if that affects the download because in browser it works)

**Comment by marius311** [comment]
They do not, that must be something else. You've forwarded the IP address in /etc/hosts correctly?

**Comment by MTRNord** [comment]
So my actual setup could than do be a problem. I run the docker on my windows maschine in vbox xD so that could be the problem. I will test that. But error is only when downloading these two files. I will re read the docs :)
